// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPackStore is an autogenerated mock type for the PackStore type
type MockPackStore struct {
	mock.Mock
}

type MockPackStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPackStore) EXPECT() *MockPackStore_Expecter {
	return &MockPackStore_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx
func (_m *MockPackStore) List(ctx context.Context) ([]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPackStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPackStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPackStore_Expecter) List(ctx interface{}) *MockPackStore_List_Call {
	return &MockPackStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockPackStore_List_Call) Run(run func(ctx context.Context)) *MockPackStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPackStore_List_Call) Return(_a0 []int, _a1 error) *MockPackStore_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPackStore_List_Call) RunAndReturn(run func(context.Context) ([]int, error)) *MockPackStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceAll provides a mock function with given fields: ctx, sizes
func (_m *MockPackStore) ReplaceAll(ctx context.Context, sizes []int) error {
	ret := _m.Called(ctx, sizes)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) error); ok {
		r0 = rf(ctx, sizes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPackStore_ReplaceAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceAll'
type MockPackStore_ReplaceAll_Call struct {
	*mock.Call
}

// ReplaceAll is a helper method to define mock.On call
//   - ctx context.Context
//   - sizes []int
func (_e *MockPackStore_Expecter) ReplaceAll(ctx interface{}, sizes interface{}) *MockPackStore_ReplaceAll_Call {
	return &MockPackStore_ReplaceAll_Call{Call: _e.mock.On("ReplaceAll", ctx, sizes)}
}

func (_c *MockPackStore_ReplaceAll_Call) Run(run func(ctx context.Context, sizes []int)) *MockPackStore_ReplaceAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int))
	})
	return _c
}

func (_c *MockPackStore_ReplaceAll_Call) Return(_a0 error) *MockPackStore_ReplaceAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPackStore_ReplaceAll_Call) RunAndReturn(run func(context.Context, []int) error) *MockPackStore_ReplaceAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPackStore creates a new instance of MockPackStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPackStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPackStore {
	mock := &MockPackStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
