// Code generated by mockery v2.52.2. DO NOT EDIT.

package mocks

import (
	context "context"
	calculator "order-pack-calculator/internal/usecase/calculator"

	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// Calculate provides a mock function with given fields: ctx, items
func (_m *MockUseCase) Calculate(ctx context.Context, items int) (*calculator.Result, error) {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for Calculate")
	}

	var r0 *calculator.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*calculator.Result, error)); ok {
		return rf(ctx, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *calculator.Result); ok {
		r0 = rf(ctx, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*calculator.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_Calculate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Calculate'
type MockUseCase_Calculate_Call struct {
	*mock.Call
}

// Calculate is a helper method to define mock.On call
//   - ctx context.Context
//   - items int
func (_e *MockUseCase_Expecter) Calculate(ctx interface{}, items interface{}) *MockUseCase_Calculate_Call {
	return &MockUseCase_Calculate_Call{Call: _e.mock.On("Calculate", ctx, items)}
}

func (_c *MockUseCase_Calculate_Call) Run(run func(ctx context.Context, items int)) *MockUseCase_Calculate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockUseCase_Calculate_Call) Return(_a0 *calculator.Result, _a1 error) *MockUseCase_Calculate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_Calculate_Call) RunAndReturn(run func(context.Context, int) (*calculator.Result, error)) *MockUseCase_Calculate_Call {
	_c.Call.Return(run)
	return _c
}

// ListPackSizes provides a mock function with given fields: ctx
func (_m *MockUseCase) ListPackSizes(ctx context.Context) ([]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPackSizes")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_ListPackSizes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPackSizes'
type MockUseCase_ListPackSizes_Call struct {
	*mock.Call
}

// ListPackSizes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUseCase_Expecter) ListPackSizes(ctx interface{}) *MockUseCase_ListPackSizes_Call {
	return &MockUseCase_ListPackSizes_Call{Call: _e.mock.On("ListPackSizes", ctx)}
}

func (_c *MockUseCase_ListPackSizes_Call) Run(run func(ctx context.Context)) *MockUseCase_ListPackSizes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUseCase_ListPackSizes_Call) Return(_a0 []int, _a1 error) *MockUseCase_ListPackSizes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_ListPackSizes_Call) RunAndReturn(run func(context.Context) ([]int, error)) *MockUseCase_ListPackSizes_Call {
	_c.Call.Return(run)
	return _c
}

// ReplacePackSizes provides a mock function with given fields: ctx, sizes
func (_m *MockUseCase) ReplacePackSizes(ctx context.Context, sizes []int) error {
	ret := _m.Called(ctx, sizes)

	if len(ret) == 0 {
		panic("no return value specified for ReplacePackSizes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) error); ok {
		r0 = rf(ctx, sizes)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUseCase_ReplacePackSizes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplacePackSizes'
type MockUseCase_ReplacePackSizes_Call struct {
	*mock.Call
}

// ReplacePackSizes is a helper method to define mock.On call
//   - ctx context.Context
//   - sizes []int
func (_e *MockUseCase_Expecter) ReplacePackSizes(ctx interface{}, sizes interface{}) *MockUseCase_ReplacePackSizes_Call {
	return &MockUseCase_ReplacePackSizes_Call{Call: _e.mock.On("ReplacePackSizes", ctx, sizes)}
}

func (_c *MockUseCase_ReplacePackSizes_Call) Run(run func(ctx context.Context, sizes []int)) *MockUseCase_ReplacePackSizes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int))
	})
	return _c
}

func (_c *MockUseCase_ReplacePackSizes_Call) Return(_a0 error) *MockUseCase_ReplacePackSizes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUseCase_ReplacePackSizes_Call) RunAndReturn(run func(context.Context, []int) error) *MockUseCase_ReplacePackSizes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
